name: Gerar gráfico de contribuição do Pac-Man

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar animação Pac-Man
        uses: Platane/snk@v3
        with:
          github_user_name: R4i5and0
          outputs: |
            dist/pacman.svg

      - name: Commitar arquivo no repositório
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/pacman.svg
          git commit -m "Atualiza gráfico Pac-Man" || echo "Nenhuma mudança para commitar"
          git push
