name: Gerar gráfico de contribuição do Pac-Man

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Baixar gerador de animação
        uses: Platane/snk@v3
        with:
          github_user_name: R4i5and0
          outputs: |
            dist/pacman.svg

      - name: Upload do artefato (arquivo gerado)
        uses: actions/upload-artifact@v4
        with:
          name: pacman-result
          path: dist/pacman.svg

      - name: Comitar o arquivo no README
        run: |
          mkdir -p dist
          mv dist/pacman.svg pacman.svg
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pacman.svg
          git commit -m "Atualiza gráfico Pac-Man"
          git push
